//Login using email id details actions
export const EMAIL_LOGIN_START = "EMAIL_LOGIN_START";
export const EMAIL_LOGIN_SUCCESS = "EMAIL_LOGIN_SUCCESS";
export const EMAIL_LOGIN_ERROR = "EMAIL_LOGIN_ERROR";
export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const FORGOT_PASSWORD_START = "FORGOT_PASSWORD_START";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";

// student action
export const ADD_STUDENT_START = "ADD_STUDENT_START";
export const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS";
export const ADD_STUDENT_ERROR = "ADD_STUDENT_ERROR";

export const GET_ALL_STUDENTS_DATA_START = "GET_ALL_STUDENTS_DATA_START";
export const GET_ALL_STUDENTS_DATA_SUCCESS = "GET_ALL_STUDENTS_DATA_SUCCESS";
export const GET_ALL_STUDENTS_DATA_ERROR = "GET_ALL_STUDENTS_DATA_ERROR";

export const UPDATE_STUDENTS_START = "UPDATE_STUDENTS_START";
export const UPDATE_STUDENTS_SUCCESS = "UPDATE_STUDENTS_SUCCESS";
export const UPDATE_STUDENTS_ERROR = "UPDATE_STUDENTS_ERROR";

export const DELETE_STUDENTS_START = "DELETE_STUDENTS_START";
export const DELETE_STUDENTS_SUCCESS = "DELETE_STUDENTS_SUCCESS";
export const DELETE_STUDENTS_ERROR = "DELETE_STUDENTS_ERROR";

// teaching staff
export const ADD_TEACHING_STAFF_START = "ADD_TEACHING_STAFF_START";
export const ADD_TEACHING_STAFF_SUCCESS = "ADD_TEACHING_STAFF_SUCCESS";
export const ADD_TEACHING_STAFF_ERROR = "ADD_TEACHING_STAFF_ERROR";

export const GET_ALL_TEACHING_STAFF_DATA_START = "GET_ALL_TEACHING_STAFF_DATA_START";
export const GET_ALL_TEACHING_STAFF_DATA_SUCCESS = "GET_ALL_TEACHING_STAFF_DATA_SUCCESS";
export const GET_ALL_TEACHING_STAFF_DATA_ERROR = "GET_ALL_TEACHING_STAFF_DATA_ERROR";

export const UPDATE_TEACHING_STAFF_START = "UPDATE_TEACHING_STAFF_START";
export const UPDATE_TEACHING_STAFF_SUCCESS = "UPDATE_TEACHING_STAFF_SUCCESS";
export const UPDATE_TEACHING_STAFF_ERROR = "UPDATE_TEACHING_STAFF_ERROR";

export const DELETE_TEACHING_STAFF_START = "DELETE_TEACHING_STAFF_START";
export const DELETE_TEACHING_STAFF_SUCCESS = "DELETE_TEACHING_STAFF_SUCCESS";
export const DELETE_TEACHING_STAFF_ERROR = "DELETE_TEACHING_STAFF_ERROR";

// Non teaching staff
export const ADD_NON_TEACHING_STAFF_START = "ADD_NON_TEACHING_STAFF_START";
export const ADD_NON_TEACHING_STAFF_SUCCESS = "ADD_NON_TEACHING_STAFF_SUCCESS";
export const ADD_NON_TEACHING_STAFF_ERROR = "ADD_NON_TEACHING_STAFF_ERROR";

export const GET_ALL_NON_TEACHING_STAFF_DATA_START = "GET_ALL_NON_TEACHING_STAFF_DATA_START";
export const GET_ALL_NON_TEACHING_STAFF_DATA_SUCCESS = "GET_ALL_NON_TEACHING_STAFF_DATA_SUCCESS";
export const GET_ALL_NON_TEACHING_STAFF_DATA_ERROR = "GET_ALL_NON_TEACHING_STAFF_DATA_ERROR";

export const UPDATE_NON_TEACHING_STAFF_START = "UPDATE_NON_TEACHING_STAFF_START";
export const UPDATE_NON_TEACHING_STAFF_SUCCESS = "UPDATE_NON_TEACHING_STAFF_SUCCESS";
export const UPDATE_NON_TEACHING_STAFF_ERROR = "UPDATE_NON_TEACHING_STAFF_ERROR";

export const DELETE_NON_TEACHING_STAFF_START = "DELETE_NON_TEACHING_STAFF_START";
export const DELETE_NON_TEACHING_STAFF_SUCCESS = "DELETE_NON_TEACHING_STAFF_SUCCESS";
export const DELETE_NON_TEACHING_STAFF_ERROR = "DELETE_NON_TEACHING_STAFF_ERROR";

// bus list
export const ADD_BUS_LIST_START = "ADD_BUS_LIST_START";
export const ADD_BUS_LIST_SUCCESS = "ADD_BUS_LIST_SUCCESS";
export const ADD_BUS_LIST_ERROR = "ADD_BUS_LIST_ERROR";

export const GET_ALL_BUS_LIST_DATA_START = "GET_ALL_BUS_LIST_DATA_START";
export const GET_ALL_BUS_LIST_DATA_SUCCESS = "GET_ALL_BUS_LIST_DATA_SUCCESS";
export const GET_ALL_BUS_LIST_DATA_ERROR = "GET_ALL_BUS_LIST_DATA_ERROR";

export const UPDATE_BUS_LIST_START = "UPDATE_BUS_LIST_START";
export const UPDATE_BUS_LIST_SUCCESS = "UPDATE_BUS_LIST_SUCCESS";
export const UPDATE_BUS_LIST_ERROR = "UPDATE_BUS_LIST_ERROR";

export const DELETE_BUS_LIST_START = "DELETE_BUS_LIST_START";
export const DELETE_BUS_LIST_SUCCESS = "DELETE_BUS_LIST_SUCCESS";
export const DELETE_BUS_LIST_ERROR = "DELETE_BUS_LIST_ERROR";

// bus route
export const ADD_BUS_ROUTE_START = "ADD_BUS_ROUTE_START";
export const ADD_BUS_ROUTE_SUCCESS = "ADD_BUS_ROUTE_SUCCESS";
export const ADD_BUS_ROUTE_ERROR = "ADD_BUS_ROUTE_ERROR";

export const GET_ALL_BUS_ROUTE_DATA_START = "GET_ALL_BUS_ROUTE_DATA_START";
export const GET_ALL_BUS_ROUTE_DATA_SUCCESS = "GET_ALL_BUS_ROUTE_DATA_SUCCESS";
export const GET_ALL_BUS_ROUTE_DATA_ERROR = "GET_ALL_BUS_ROUTE_DATA_ERROR";

export const UPDATE_BUS_ROUTE_START = "UPDATE_BUS_ROUTE_START";
export const UPDATE_BUS_ROUTE_SUCCESS = "UPDATE_BUS_ROUTE_SUCCESS";
export const UPDATE_BUS_ROUTE_ERROR = "UPDATE_BUS_ROUTE_ERROR";

export const DELETE_BUS_ROUTE_START = "DELETE_BUS_ROUTE_START";
export const DELETE_BUS_ROUTE_SUCCESS = "DELETE_BUS_ROUTE_SUCCESS";
export const DELETE_BUS_ROUTE_ERROR = "DELETE_BUS_ROUTE_ERROR";

// bus staff
export const ADD_BUS_STAFF_START = "ADD_BUS_STAFF_START";
export const ADD_BUS_STAFF_SUCCESS = "ADD_BUS_STAFF_SUCCESS";
export const ADD_BUS_STAFF_ERROR = "ADD_BUS_STAFF_ERROR";

export const GET_ALL_BUS_STAFF_DATA_START = "GET_ALL_BUS_STAFF_DATA_START";
export const GET_ALL_BUS_STAFF_DATA_SUCCESS = "GET_ALL_BUS_STAFF_DATA_SUCCESS";
export const GET_ALL_BUS_STAFF_DATA_ERROR = "GET_ALL_BUS_STAFF_DATA_ERROR";

export const UPDATE_BUS_STAFF_START = "UPDATE_BUS_STAFF_START";
export const UPDATE_BUS_STAFF_SUCCESS = "UPDATE_BUS_STAFF_SUCCESS";
export const UPDATE_BUS_STAFF_ERROR = "UPDATE_BUS_STAFF_ERROR";

export const DELETE_BUS_STAFF_START = "DELETE_BUS_STAFF_START";
export const DELETE_BUS_STAFF_SUCCESS = "DELETE_BUS_STAFF_SUCCESS";
export const DELETE_BUS_STAFF_ERROR = "DELETE_BUS_STAFF_ERROR";

// fees
export const ADD_FEES_START = "ADD_FEES_START";
export const ADD_FEES_SUCCESS = "ADD_FEES_SUCCESS";
export const ADD_FEES_ERROR = "ADD_FEES_ERROR";

export const GET_ALL_FEES_DATA_START = "GET_ALL_FEES_DATA_START";
export const GET_ALL_FEES_DATA_SUCCESS = "GET_ALL_FEES_DATA_SUCCESS";
export const GET_ALL_FEES_DATA_ERROR = "GET_ALL_FEES_DATA_ERROR";

export const UPDATE_FEES_START = "UPDATE_FEES_START";
export const UPDATE_FEES_SUCCESS = "UPDATE_FEES_SUCCESS";
export const UPDATE_FEES_ERROR = "UPDATE_FEES_ERROR";

export const DELETE_FEES_START = "DELETE_FEES_START";
export const DELETE_FEES_SUCCESS = "DELETE_FEES_SUCCESS";
export const DELETE_FEES_ERROR = "DELETE_FEES_ERROR";

// payroll
export const ADD_PAYROLL_START = "ADD_PAYROLL_START";
export const ADD_PAYROLL_SUCCESS = "ADD_PAYROLL_SUCCESS";
export const ADD_PAYROLL_ERROR = "ADD_PAYROLL_ERROR";

export const GET_ALL_PAYROLL_DATA_START = "GET_ALL_PAYROLL_DATA_START";
export const GET_ALL_PAYROLL_DATA_SUCCESS = "GET_ALL_PAYROLL_DATA_SUCCESS";
export const GET_ALL_PAYROLL_DATA_ERROR = "GET_ALL_PAYROLL_DATA_ERROR";

export const UPDATE_PAYROLL_START = "UPDATE_PAYROLL_START";
export const UPDATE_PAYROLL_SUCCESS = "UPDATE_PAYROLL_SUCCESS";
export const UPDATE_PAYROLL_ERROR = "UPDATE_PAYROLL_ERROR";

export const DELETE_PAYROLL_START = "DELETE_PAYROLL_START";
export const DELETE_PAYROLL_SUCCESS = "DELETE_PAYROLL_SUCCESS";
export const DELETE_PAYROLL_ERROR = "DELETE_PAYROLL_ERROR";

// user profile
export const GET_USER_PROFILE_START = "GET_USER_PROFILE_START";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_ERROR = "GET_USER_PROFILE_ERROR";

export const UPDATE_USER_PROFILE_START = "UPDATE_USER_PROFILE_START";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_ERROR = "UPDATE_USER_PROFILE_ERROR";

//  class
export const ADD_CLASS_START = "ADD_CLASS_START";
export const ADD_CLASS_SUCCESS = "ADD_CLASS_SUCCESS";
export const ADD_CLASS_ERROR = "ADD_CLASS_ERROR";

export const GET_ALLCLASSES_START = "GET_ALLCLASSES_START";
export const GET_ALLCLASSES_SUCCESS = "AGET_ALLCLASSES_SUCCESS";
export const GET_ALLCLASSES_ERROR = "GET_ALLCLASSES_ERROR";

export const DELETE_CLASS_START = "DELETE_CLASS_START";
export const DELETE_CLASS_SUCCESS = "DELETE_CLASS_SUCCESS";
export const DELETE_CLASS_ERROR = "DELETE_CLASS_ERROR";

export const EDIT_CLASS_START = "EDIT_CLASS_START";
export const EDIT_CLASS_SUCCESS = "EDIT_CLASS_SUCCESS";
export const EDIT_CLASS_ERROR = "EDIT_CLASS_ERROR";

export const ADD_CLASSTIMETABLE_START = "ADD_CLASSTIMETABLE_START";
export const ADD_CLASSTIMETABLE_SUCCESS = "ADD_CLASSTIMETABLE_SUCCESS";
export const ADD_CLASSTIMETABLE_ERROR = "ADD_CLASSTIMETABLE_ERROR";

export const GET_CLASSTIMETABLE_START = "GET_CLASSTIMETABLE_START";
export const GET_CLASSTIMETABLE_SUCCESS = "GET_CLASSTIMETABLE_SUCCESS";
export const GET_CLASSTIMETABLE_ERROR = "GET_CLASSTIMETABLE_ERROR";

export const DELETE_CLASSTIMETABLE_START = "DELETE_CLASSTIMETABLE_START";
export const DELETE_CLASSTIMETABLE_SUCCESS = "DELETE_CLASSTIMETABLE_SUCCESS";
export const DELETE_CLASSTIMETABLE_ERROR = "DELETE_CLASSTIMETABLE_ERROR";

export const UPDATE_CLASSTIMETABLE_START = "UPDATE_CLASSTIMETABLE_START";
export const UPDATE_CLASSTIMETABLE_SUCCESS = "UPDATE_CLASSTIMETABLE_SUCCESS";
export const UPDATE_CLASSTIMETABLE_ERROR = "UPDATE_CLASSTIMETABLE_ERROR";

export const ADD_SECTION_START = "ADD_SECTION_START";
export const ADD_SECTION_SUCCESS = "ADD_SECTION_SUCCESS";
export const ADD_SECTION_ERROR = "ADD_SECTION_ERROR";

export const GET_ALLSECTION_START = "GET_ALLSECTION_START";
export const GET_ALLSECTION_SUCCESS = "GET_ALLSECTION_SUCCESS";
export const GET_ALLSECTION_ERROR = "GET_ALLSECTION_ERROR";

export const UPDATE_SECTION_START = "UPDATE_SECTION_START";
export const UPDATE_SECTION_SUCCESS = "UPDATE_SECTION_SUCCESS";
export const UPDATE_SECTION_ERROR = "UPDATE_SECTION_ERROR";

export const DELETE_SECTION_START = "DELETE_SECTION_START";
export const DELETE_SECTION_SUCCESS = "DELETE_SECTION_SUCCESS"; 
export const DELETE_SECTION_ERROR = "DELETE_SECTION_ERROR"; 

//holiday
export const ADD_HOLIDAY_START = "ADD_HOLIDAY_START";
export const ADD_HOLIDAY_SUCCESS = "ADD_HOLIDAY_SUCCESS";
export const ADD_HOLIDAY_ERROR = "ADD_HOLIDAY_ERROR";

export const GET_HOLIDAY_START = "GET_HOLIDAY_START";
export const GET_HOLIDAY_SUCCESS = "GET_HOLIDAY_SUCCESS";
export const GET_HOLIDAY_ERROR = "GET_HOLIDAY_ERROR";

export const UPDATE_HOLIDAY_START = "UPDATE_HOLIDAY_START";
export const UPDATE_HOLIDAY_SUCCESS = "UPDATE_HOLIDAY_SUCCESS";
export const UPDATE_HOLIDAY_ERROR = "UPDATE_HOLIDAY_ERROR";

export const DELETE_HOLIDAY_START = "DELETE_HOLIDAY_START";
export const DELETE_HOLIDAY_SUCCESS = "DELETE_HOLIDAY_SUCCESS";
export const DELETE_HOLIDAY_ERROR = "DELETE_HOLIDAY_ERROR";

//notice board
export const ADD_NOTICEBOARD_START = "ADD_NOTICEBOARD_START";
export const ADD_NOTICEBOARD_SUCCESS = "ADD_NOTICEBOARD_SUCCESS";    
export const ADD_NOTICEBOARD_ERROR = "ADD_NOTICEBOARD_ERROR";
 
export const GET_NOTICEBOARD_START = "GET_NOTICEBOARD_START";
export const GET_NOTICEBOARD_SUCCESS = "GET_NOTICEBOARD_SUCCESS"; 
export const GET_NOTICEBOARD_ERROR = "GET_NOTICEBOARD_ERROR"; 

export const UPDATE_NOTICEBOARD_START = "UPDATE_NOTICEBOARD_START";
export const UPDATE_NOTICEBOARD_SUCCESS = "UPDATE_NOTICEBOARD_SUCCESS"; 
export const UPDATE_NOTICEBOARD_ERROR = "UPDATE_NOTICEBOARD_ERROR"; 

export const DELETE_NOTICEBOARD_START = "DELETE_NOTICEBOARD_START";
export const DELETE_NOTICEBOARD_SUCCESS = "DELETE_NOTICEBOARD_SUCCESS"; 
export const DELETE_NOTICEBOARD_ERROR = "DELETE_NOTICEBOARD_ERROR";

export const SEARCH_NOTICEBOARD_START = "SEARCH_NOTICEBOARD_START";
export const SEARCH_NOTICEBOARD_SUCCESS = "SEARCH_NOTICEBOARD_SUCCESS"; 
export const SEARCH_NOTICEBOARD_ERROR = "SEARCH_NOTICEBOARD_ERROR";


//setings update password
export const UPDATE_PASSWORD_START = "UPDATE_PASSWORD_START";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS"; 
export const UPDATE_PASSWORD_ERROR = "UPDATE_PASSWORD_ERROR";   

//post blog
export const ADD_BLOG_START = "ADD_BLOG_START"; 
export const ADD_BLOG_SUCCESS = "ADD_BLOG_SUCCESS";
export const ADD_BLOG_ERROR = "ADD_BLOG_ERROR";

//get all blog
export const GET_ALL_BLOG_START = "GET_ALL_BLOG_START"; 
export const GET_ALL_BLOG_SUCCESS = "GET_ALL_BLOG_SUCCESS";
export const GET_ALL_BLOG_ERROR = "GET_ALL_BLOG_ERROR";

//update blog
export const UPDATE_BLOG_START = "UPDATE_BLOG_START";   
export const UPDATE_BLOG_SUCCESS = "UPDATE_BLOG_SUCCESS";
export const UPDATE_BLOG_ERROR = "UPDATE_BLOG_ERROR";

//delete blog
export const DELETE_BLOG_START = "DELETE_BLOG_START";   
export const DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS";
export const DELETE_BLOG_ERROR = "DELETE_BLOG_ERROR";

//add comment
export const ADD_COMMENT_START = "ADD_COMMENT_START";   
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_ERROR = "ADD_COMMENT_ERROR";

export const GET_COMMENT_START = "GET_COMMENT_START";
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS";   
export const GET_COMMENT_ERROR = "GET_COMMENT_ERROR";

export const GET_ALL_NOTIFICATIONS_START = "GET_ALL_NOTIFICATIONS_START";
export const GET_ALL_NOTIFICATIONS_SUCCESS = "GET_ALL_NOTIFICATIONS_SUCCESS";
export const GET_ALL_NOTIFICATIONS_ERROR = "GET_ALL_NOTIFICATIONS_ERROR";
export const GET_ALL_TEACHERS_TIMETABLE_START = "GET_ALL_TEACHERS_TIMETABLE_START";
export const GET_ALL_TEACHERS_TIMETABLE_SUCCESS = "GET_ALL_TEACHERS_TIMETABLE_SUCCESS";
export const GET_ALL_TEACHERS_TIMETABLE_ERROR = "GET_ALL_TEACHERS_TIMETABLE_ERROR";

export const ADD_TEACHERS_TIMETABLE_START = "ADD_TEACHERS_TIMETABLE_START";
export const ADD_TEACHERS_TIMETABLE_SUCCESS = "ADD_TEACHERS_TIMETABLE_SUCCESS";
export const ADD_TEACHERS_TIMETABLE_ERROR = "ADD_TEACHERS_TIMETABLE_ERROR";

export const UPDATE_TEACHERS_TIMETABLE_START = "UPDATE_TEACHERS_TIMETABLE_START";
export const UPDATE_TEACHERS_TIMETABLE_SUCCESS = "UPDATE_TEACHERS_TIMETABLE_SUCCESS";
export const UPDATE_TEACHERS_TIMETABLE_ERROR = "UPDATE_TEACHERS_TIMETABLE_ERROR";

export const DELETE_TEACHERS_TIMETABLE_START = "DELETE_TEACHERS_TIMETABLE_START";
export const DELETE_TEACHERS_TIMETABLE_SUCCESS = "DELETE_TEACHERS_TIMETABLE_SUCCESS";
export const DELETE_TEACHERS_TIMETABLE_ERROR = "DELETE_TEACHERS_TIMETABLE_ERROR";
 

   